### PR TITLE
Testing Your Ruby Code -Advanced Building Blocks - Enumerable

### PR DESCRIPTION
**Pull request by verissimohenry**
During the program, use RSpec every time you do something related to testing in Ruby or Rails.
For this assignment, build tests for Advanced Building Blocks - Enumerable
In this pull request, I create a test with RSpec for the following: We write methods about,my_each, my_each_with_index, my_select,#my_all?# my_any? #my_none?# my_count, #my_map, #my_inject, and last we use proc in #my_map

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: : 
----------
Hello @verissimohenry :wave: You did a pretty good job in this project. :1st_place_medal: 
TO HIGHLIGHT: 

- You have a great number of tests.
- Good commit messages. 

However, there are a few changes to make to complete this project. :hammer_and_wrench: see them below :eyes: :point_down: 
------------
- [x] Please rename your `enumerables_test.rb` file to `enumerables_spec.rb` so when you run `rspec` on your terminal automatically the RSpec going to run this file. All the files that you want to run with RSpec must be ending with `_spec`
- [x] Please inside your `enumerables_test.rb` file, write the correct path of the enumerables. You are misspelling, you write `require_relative '../enumerables'` and it must be `require_relative '../enumerable'`. That is causing problems running the RSpec. 
- [x] Please write in your Readme file step-by-step about how to run the RSpec. 
- [x] Changes the pull request description. Remember that you must write in this description what are the files you create/changes, that you want to merge. E.g you can write `In this pull request I create a test with RSpec for the followings: #my_all, my_any, etc`
- [x] Please add negative scenarios for your RSpec, You only create a negative scenario for #multiply_els.
- [x] You wrap all your test inside the `describe '#my_all'` Please move them out. 
-----------------
Make the required changes :point_up_2: and send it again for review. 
Reach me on SLACK if you have any questions. 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!!

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUESTED 🔴 ♻️ 

Hello there @verissimohenry 👋🏾 congratulations on making it this far in this milestone. You have worked on the comments left y the TSE. Your tests are passing . However you forgot to do the following ⬇️ 

- [ ] Add tests for `my_count` method 😄 

That's all :smile: kindly submit another review when done.

_If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me @mimipeshy. I will be happy to help_
Regards
Peris Ndanu

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @verissimohenry ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by verissimohenry** [comment]
Thank you.

**Pull request merged**
